name: web-build
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  rmd-render-job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.1'
      - name: Install linux dependencies
        run: |
          sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev libopenblas-base
      - name: Cache R packages
        id: cache-rp
        uses: actions/cache@v1
        with:
          path: "/home/runner/work/_temp/Library"
          key: ${{ runner.os }}-cache-rp
      - name: Install R packages
      	if: steps.cache-rp.outputs.cache-hit != 'true'
        run: |
          Rscript -e "install.packages('devtools')"
      - run: |
          if [[ $(dpkg -l | grep -E '^ii' | grep r-3.6.1) ]]; then
           echo "there are files"
          else
           echo "no files found"
          fi
      - run: |
          Rscript -e ".libPaths()"
