name: web-build
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  rmd-render-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.1'
      - uses: r-lib/actions/setup-pandoc@master
      - name: Check R installation and define variables
        run: |
          Rscript -e "print('R installation works!')"
          echo "::set-env name=path_repo::$(pwd)"
          echo "Path repo: ${path_repo}"
          echo "::set-env name=path_export::$(grep -E '^output_dir' _site.yml | sed 's/^output_dir://' | xargs)"
          echo "Path export: ${path_export}"
          ls -lh
      - name: Pull gh-pages, check duplicate folder, copy rendered folder
        run: |
          git clone --single-branch --branch gh-pages "https://${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}" tmprepo
          cd tmprepo
          if [ -d $path_export ]; then
            echo "Directory ${path_export} already exists. Removing the directory."
            git rm -r $path_export
            git commit -m "Old directory ${path_export} deleted."
          fi
          ls -lh

