name: web-build
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  rmd-render-job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.1'
      - run: |
          dpkg -l | grep -E '^ii' | grep R
      - run: |
          Rscript -e ".libPaths()"
